import type { Metadata } from "next";
import "./globals.scss";
import NavBar from "@/components/Header/NavBar";
import Whatsapp from "@/components/WhatsApp";
import Call from "@/components/Call";
import Footer2 from "@/components/Footer/Footer2";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <NavBar />
        {children}
        <Footer2 />
        <Whatsapp />
        <Call />
      </body>
    </html>
  );
}
